/**
 * DOM要素参照 (DOM Elements)
 * DOMContentLoaded後にアクセスすることを前提に、ゲッターで定義
 */
export const elements = {
    get sortToggleBtn() { return document.getElementById('sortToggleBtn'); },
    get musicGrid() { return document.getElementById('musicGrid'); },
    get searchInput() { return document.getElementById('searchInput'); },
    get searchClear() { return document.getElementById('searchClear'); },
    get musicCount() { return document.getElementById('musicCount'); },
    get currentFilter() { return document.getElementById('currentFilter'); },
    get nowPlayingBar() { return document.getElementById('nowPlayingBar'); },
    get playerJacket() { return document.getElementById('playerJacket'); },
    get playerJacketImg() { return document.getElementById('playerJacketImg'); },
    get playerTitle() { return document.getElementById('playerTitle'); },
    get playerArtist() { return document.getElementById('playerArtist'); },
    get playPauseBtn() { return document.getElementById('playPauseBtn'); },
    get prevBtn() { return document.getElementById('prevBtn'); },
    get nextBtn() { return document.getElementById('nextBtn'); },
    get progressBar() { return document.getElementById('progressBar'); },
    get progressFill() { return document.getElementById('progressFill'); },
    get progressHandle() { return document.getElementById('progressHandle'); },
    get progressBuffered() { return document.getElementById('progressBuffered'); },
    get currentTime() { return document.getElementById('currentTime'); },
    get durationTime() { return document.getElementById('durationTime'); },
    get volumeBtn() { return document.getElementById('volumeBtn'); },
    get volumeSlider() { return document.getElementById('volumeSlider'); },
    get repeatBtn() { return document.getElementById('repeatBtn'); },
    get shuffleBtn() { return document.getElementById('shuffleBtn'); },
    get lyricsBtn() { return document.getElementById('lyricsBtn'); },
    get themeToggle() { return document.getElementById('themeToggle'); },
    get dynamicBg() { return document.getElementById('dynamicBg'); },

    // Modals
    get vocalModal() { return document.getElementById('vocalModal'); },
    get modalMusicTitle() { return document.getElementById('modalMusicTitle'); },
    get vocalList() { return document.getElementById('vocalList'); },
    get modalClose() { return document.getElementById('modalClose'); },
    get lyricsModal() { return document.getElementById('lyricsModal'); },
    get lyricsMusicTitle() { return document.getElementById('lyricsMusicTitle'); },
    get lyricsContainer() { return document.getElementById('lyricsContainer'); },
    get lyricsClose() { return document.getElementById('lyricsClose'); },
    get settingsModal() { return document.getElementById('settingsModal'); },
    get settingsBtn() { return document.getElementById('settingsBtn'); },
    get settingsClose() { return document.getElementById('settingsClose'); },
    get shortcutsBtn() { return document.getElementById('shortcutsBtn'); },
    get shortcutsModal() { return document.getElementById('shortcutsModal'); },
    get shortcutsClose() { return document.getElementById('shortcutsClose'); },
    get vocalPrioritySelect() { return document.getElementById('vocalPrioritySelect'); },
    get playlistsModal() { return document.getElementById('playlistsModal'); },
    get playlistMenuBtn() { return document.getElementById('playlistMenuBtn'); },
    get playlistsClose() { return document.getElementById('playlistsClose'); },
    get playlistsList() { return document.getElementById('playlistsList'); },
    get newPlaylistName() { return document.getElementById('newPlaylistName'); },
    get newPlaylistIds() { return document.getElementById('newPlaylistIds'); },
    get createPlaylistBtn() { return document.getElementById('createPlaylistBtn'); },
    get addToPlaylistModal() { return document.getElementById('addToPlaylistModal'); },
    get addToPlaylistClose() { return document.getElementById('addToPlaylistClose'); },
    get addToPlaylistList() { return document.getElementById('addToPlaylistList'); },
    get confirmModal() { return document.getElementById('confirmModal'); },
    get confirmTitle() { return document.getElementById('confirmTitle'); },
    get confirmMessage() { return document.getElementById('confirmMessage'); },
    get confirmClose() { return document.getElementById('confirmClose'); },
    get confirmCancelBtn() { return document.getElementById('confirmCancelBtn'); },
    get confirmOkBtn() { return document.getElementById('confirmOkBtn'); },

    get audioPlayer() { return document.getElementById('audioPlayer'); },
    get audioPlayerAlt() { return document.getElementById('audioPlayerAlt'); },

    // 追加要素
    get contextBar() { return document.getElementById('contextBar'); },
    get contextTitle() { return document.getElementById('contextTitle'); },
    get contextCloseBtn() { return document.getElementById('contextCloseBtn'); },
    get contextCopyBtn() { return document.getElementById('contextCopyBtn'); },
    get contextPlayBtn() { return document.getElementById('contextPlayBtn'); },
    get contextDeleteBtn() { return document.getElementById('contextDeleteBtn'); },
    get scrollToTopBtn() { return document.getElementById('scrollToTopBtn'); },
    get autoplayToggle() { return document.getElementById('autoplayToggle'); },
    get crossfadeToggle() { return document.getElementById('crossfadeToggle'); },
    get crossfadeSlider() { return document.getElementById('crossfadeSlider'); },
    get crossfadeValue() { return document.getElementById('crossfadeValue'); },
    get crossfadeSliderContainer() { return document.getElementById('crossfadeSliderContainer'); },
    get settingVolumeSlider() { return document.getElementById('settingVolumeSlider'); },
    get favBtn() { return document.getElementById('favBtn'); },

    // 統計・履歴
    get statsBtn() { return document.getElementById('statsBtn'); },
    get statsModal() { return document.getElementById('statsModal'); },
    get statsClose() { return document.getElementById('statsClose'); }
};
